name: test

on:

  push:

    branches:

      - main

jobs:

  lint:

    runs-on: ubuntu-latest

    name: Lint

    steps:

      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1

      - run: npm run lint

      - run: npm run test
